In [65]:
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split 

In [66]:
import matplotlib.pyplot as plt

In [67]:
import pandas as pd

In [68]:
iris = pd.read_excel("iris.xlsx")

In [69]:
iris[:5]

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0           0                5.1               3.5                1.4   
1           1                4.9               3.0                1.4   
2           2                4.7               3.2                1.3   
3           3                4.6               3.1                1.5   
4           4                5.0               3.6                1.4   

   petal width (cm)  target  
0               0.2       0  
1               0.2       0  
2               0.2       0  
3               0.2       0  
4               0.2       0

In [70]:
x = iris[["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"]]

In [71]:
x[:5]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [72]:
y = iris[["target"]]

In [74]:
y[5:]

target
5         0
6         0
7         0
8         0
9         0
..      ...
145       2
146       2
147       2
148       2
149       2

[145 rows x 1 columns]

In [75]:
iris_array = iris.values
x_array = x.values
labels = iris_array[:,5]
x = x_array[:]

In [76]:
x[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [77]:
type(x)

numpy.ndarray

In [78]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2)

In [79]:
x_train[:10]

array([[6.6, 3. , 4.4, 1.4],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [4.8, 3. , 1.4, 0.1],
       [5.2, 3.4, 1.4, 0.2],
       [6. , 2.2, 5. , 1.5],
       [5.9, 3. , 5.1, 1.8],
       [6.1, 2.6, 5.6, 1.4],
       [6.5, 3. , 5.8, 2.2]])

In [80]:
x_test[:5]

array([[5.1, 3.8, 1.5, 0.3],
       [6.4, 2.8, 5.6, 2.2],
       [5.6, 2.9, 3.6, 1.3],
       [6. , 2.9, 4.5, 1.5],
       [7.9, 3.8, 6.4, 2. ]])

In [81]:
 y_train[:5]

target
75       1
97       1
79       1
61       1
12       0

In [82]:
y_train2 = tf.keras.utils.to_categorical(y_train, num_classes = 3)
y_test2 = tf.keras.utils.to_categorical(y_test, num_classes = 3)

In [83]:
y_train2[:5]

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [84]:
model = tf.keras.models.Sequential()

In [85]:
model.add(tf.keras.layers.Dense(input_dim = 4, units = 100, activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units = 200, activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units = 200, activation=tf.nn.relu))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units = 3, activation=tf.nn.softmax))

In [86]:
model.compile(optimizer = 'adam', loss = tf.keras.losses.categorical_crossentropy, metrics = ['accuracy'])

In [87]:
history = model.fit(x_train, y_train2,
          epochs=200,
          batch_size=128)

Epoch 1/200
1/1 [==============================] - 0s 104ms/step - loss: 1.1529 - accuracy: 0.3333
Epoch 2/200
1/1 [==============================] - 0s 2ms/step - loss: 1.0092 - accuracy: 0.4917
Epoch 3/200
1/1 [==============================] - 0s 3ms/step - loss: 0.9229 - accuracy: 0.6083
Epoch 4/200
1/1 [==============================] - 0s 2ms/step - loss: 0.8970 - accuracy: 0.6333
Epoch 5/200
1/1 [==============================] - 0s 1000us/step - loss: 0.8708 - accuracy: 0.6000
Epoch 6/200
1/1 [==============================] - 0s 3ms/step - loss: 0.8266 - accuracy: 0.6167
Epoch 7/200
1/1 [==============================] - 0s 7ms/step - loss: 0.7254 - accuracy: 0.6583
Epoch 8/200
1/1 [==============================] - 0s 2ms/step - loss: 0.7205 - accuracy: 0.7083
Epoch 9/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6377 - accuracy: 0.7583
Epoch 10/200
1/1 [==============================] - 0s 5ms/step - loss: 0.6251 - accuracy: 0.7083
Epoch 11/200
1/1 [======

1/1 [==============================] - 0s 3ms/step - loss: 0.1364 - accuracy: 0.9417
Epoch 85/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1513 - accuracy: 0.9333
Epoch 86/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1281 - accuracy: 0.9500
Epoch 87/200
1/1 [==============================] - 0s 4ms/step - loss: 0.1096 - accuracy: 0.9500
Epoch 88/200
1/1 [==============================] - 0s 3ms/step - loss: 0.0871 - accuracy: 0.9917
Epoch 89/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1438 - accuracy: 0.9333
Epoch 90/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1179 - accuracy: 0.9333
Epoch 91/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1281 - accuracy: 0.9500
Epoch 92/200
1/1 [==============================] - 0s 7ms/step - loss: 0.1205 - accuracy: 0.9417
Epoch 93/200
1/1 [==============================] - 0s 3ms/step - loss: 0.1292 - accuracy: 0.9667
Epoch 94/200
1/1 [===============

1/1 [==============================] - 0s 3ms/step - loss: 0.1096 - accuracy: 0.9667
Epoch 168/200
1/1 [==============================] - 0s 3ms/step - loss: 0.0672 - accuracy: 0.9750
Epoch 169/200
1/1 [==============================] - 0s 2ms/step - loss: 0.0746 - accuracy: 0.9833
Epoch 170/200
1/1 [==============================] - 0s 3ms/step - loss: 0.0848 - accuracy: 0.9833
Epoch 171/200
1/1 [==============================] - 0s 3ms/step - loss: 0.0830 - accuracy: 0.9833
Epoch 172/200
1/1 [==============================] - 0s 3ms/step - loss: 0.0568 - accuracy: 0.9917
Epoch 173/200
1/1 [==============================] - 0s 3ms/step - loss: 0.0998 - accuracy: 0.9500
Epoch 174/200
1/1 [==============================] - 0s 2ms/step - loss: 0.0890 - accuracy: 0.9750
Epoch 175/200
1/1 [==============================] - 0s 3ms/step - loss: 0.0969 - accuracy: 0.9583
Epoch 176/200
1/1 [==============================] - 0s 4ms/step - loss: 0.0780 - accuracy: 0.9667
Epoch 177/200
1/1 [=====

In [88]:
score = model.evaluate(x_test, y_test2, batch_size=128)

1/1 [==============================] - 0s 2ms/step - loss: 0.0712 - accuracy: 0.9667


In [89]:
print(score)

[0.07116396725177765, 0.9666666388511658]


In [90]:
predict = model.predict(x_test)

In [96]:
predict[:5]*100

array([[9.99999313e+01, 6.62522871e-05, 1.42473869e-12],
       [1.84885596e-06, 1.24039195e-01, 9.98759613e+01],
       [3.93751204e-01, 9.95956039e+01, 1.06546832e-02],
       [1.55442376e-02, 9.90871582e+01, 8.97289455e-01],
       [1.26064580e-04, 4.16352959e+01, 5.83645821e+01]], dtype=float32)

In [93]:
y_test2[:5]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [98]:
predict_class = model.predict_classes(x_test)
predict_class

array([0, 2, 1, 1, 2, 2, 0, 1, 0, 1, 2, 1, 1, 1, 1, 0, 0, 0, 2, 1, 1, 2,
       0, 0, 0, 2, 0, 2, 1, 1], dtype=int64)

In [110]:
y_test

target
19        0
132       2
64        1
78        1
131       2
144       2
48        0
50        1
15        0
92        1
110       2
133       2
86        1
85        1
76        1
34        0
21        0
5         0
106       2
93        1
74        1
125       2
6         0
24        0
43        0
127       2
46        0
120       2
84        1
99        1

In [109]:
y_predict = pd.DataFrame(predict_class, columns = ["y_predict"])
y_predict

y_predict
0           0
1           2
2           1
3           1
4           2
5           2
6           0
7           1
8           0
9           1
10          2
11          1
12          1
13          1
14          1
15          0
16          0
17          0
18          2
19          1
20          1
21          2
22          0
23          0
24          0
25          2
26          0
27          2
28          1
29          1

In [111]:
y_test_array = y_test.values

In [112]:
y_test_array

array([[0],
       [2],
       [1],
       [1],
       [2],
       [2],
       [0],
       [1],
       [0],
       [1],
       [2],
       [2],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [2],
       [1],
       [1],
       [2],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [1],
       [1]], dtype=int64)